// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Syn {
    #[prost(bytes = "vec", tag = "1")]
    pub observed_underlay: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Ack {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<BzzAddress>,
    #[prost(uint64, tag = "2")]
    pub network_id: u64,
    #[prost(bool, tag = "3")]
    pub full_node: bool,
    /// v14-only: nonce sits at the Ack level. v15 places it inside
    /// BzzAddress where it's part of the signed payload.
    #[prost(bytes = "vec", tag = "4")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "99")]
    pub welcome_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SynAck {
    #[prost(message, optional, tag = "1")]
    pub syn: ::core::option::Option<Syn>,
    #[prost(message, optional, tag = "2")]
    pub ack: ::core::option::Option<Ack>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BzzAddress {
    #[prost(bytes = "vec", tag = "1")]
    pub underlay: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub overlay: ::prost::alloc::vec::Vec<u8>,
    /// v15 fields. Old peers don't send these (proto3 defaults to
    /// zero), so we discriminate by which handshake protocol version
    /// was negotiated, not by inspecting these field values.
    #[prost(bytes = "vec", tag = "4")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "5")]
    pub timestamp: i64,
    #[prost(bytes = "vec", tag = "6")]
    pub chequebook_address: ::prost::alloc::vec::Vec<u8>,
}
