// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Peers {
    #[prost(message, repeated, tag = "1")]
    pub peers: ::prost::alloc::vec::Vec<BzzAddress>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BzzAddress {
    #[prost(bytes = "vec", tag = "1")]
    pub underlay: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub overlay: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
    /// v2.0.0 fields. Older peers don't send these (proto3 defaults
    /// to zero); their absence is fine on receive (we ignore them
    /// when negotiating v1.1.0).
    #[prost(int64, tag = "5")]
    pub timestamp: i64,
    #[prost(bytes = "vec", tag = "6")]
    pub chequebook_address: ::prost::alloc::vec::Vec<u8>,
}
