// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnnouncePaymentThreshold {
    #[prost(bytes = "vec", tag = "1")]
    pub payment_threshold: ::prost::alloc::vec::Vec<u8>,
}
