// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Request {
    #[prost(bytes = "vec", tag = "1")]
    pub addr: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Delivery {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub stamp: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub err: ::prost::alloc::string::String,
}
