// This file is @generated by prost-build.
/// Inbound request: bee asks "give me your status".
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Get {}
/// Outbound response: we serve plausible-looking values. The fields
/// that bee's `salud.go::salud()` actually checks against the network
/// medians are CommittedDepth, ConnectedPeers, BatchCommitment, and
/// response duration (measured externally). Other fields are reported
/// but not gated on. See `cheques.rs` module docs for the gating
/// formulae.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Snapshot {
    #[prost(uint64, tag = "1")]
    pub reserve_size: u64,
    #[prost(double, tag = "2")]
    pub pullsync_rate: f64,
    #[prost(uint32, tag = "3")]
    pub storage_radius: u32,
    #[prost(uint64, tag = "4")]
    pub connected_peers: u64,
    #[prost(uint64, tag = "5")]
    pub neighborhood_size: u64,
    #[prost(string, tag = "6")]
    pub bee_mode: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub batch_commitment: u64,
    #[prost(bool, tag = "8")]
    pub is_reachable: bool,
    #[prost(uint64, tag = "9")]
    pub reserve_size_within_radius: u64,
    #[prost(uint64, tag = "10")]
    pub last_synced_block: u64,
    #[prost(uint32, tag = "11")]
    pub committed_depth: u32,
    #[prost(map = "string, string", tag = "12")]
    pub metrics:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
