// This file is @generated by prost-build.
/// Sent once per peer connection (ConnectIn/ConnectOut) to advertise
/// the Ethereum address that owns/controls the cheques we issue. On
/// bee's side this populates `Swap.Handshake(peer, beneficiary)`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Handshake {
    #[prost(bytes = "vec", tag = "1")]
    pub beneficiary: ::prost::alloc::vec::Vec<u8>,
}
/// Sent on a fresh `swap` substream every time we want to pay a peer.
/// `Cheque` is JSON of `chequebook.SignedCheque{Chequebook, Beneficiary,
/// CumulativePayout, Signature}`. The receiver verifies the EIP-712
/// signature recovers to `chequebook.issuer()` (on-chain).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmitCheque {
    #[prost(bytes = "vec", tag = "1")]
    pub cheque: ::prost::alloc::vec::Vec<u8>,
}
