// Build the gateway: bundle the TS entry points with esbuild, copy static
// files from public/, and vendor the hoverfly wasm package from the repo's
// pkg/ (built via `cargo build --target wasm32-... && wasm-bindgen`).

import * as esbuild from 'esbuild'
import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, rmSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const dist = resolve(here, 'dist')
const assets = resolve(dist, '__gw__')
const pkg = resolve(here, '../../pkg')
const watch = process.argv.includes('--watch')

const entryPoints = {
  landing: resolve(here, 'src/app/landing.ts'),
  boot: resolve(here, 'src/boot/boot.ts'),
  sw: resolve(here, 'src/sw/sw.ts'),
  frame: resolve(here, 'src/frame/frame.ts'),
  daemon: resolve(here, 'src/daemon/daemon.ts')
}

function copyStatic () {
  cpSync(resolve(here, 'public'), dist, { recursive: true })
  // public/__gw__/peers.ws.json is a symlink to the repo-root peers.ws.json
  // (regenerated by the refresh-peers workflow). cpSync's `dereference`
  // option is ignored for entries nested inside a recursive copy, so
  // materialize it by hand — dist/ must contain a real file, not a symlink,
  // for the deployed artifact to be self-contained.
  const peersWs = resolve(dist, '__gw__/peers.ws.json')
  rmSync(peersWs, { force: true })
  copyFileSync(resolve(here, 'public/__gw__/peers.ws.json'), peersWs)
  if (existsSync(pkg)) {
    cpSync(pkg, resolve(assets, 'hoverfly'), { recursive: true })
  } else {
    console.warn(`\n  ⚠  ${pkg} not found — build the wasm first:\n` +
      '     RUSTUP_TOOLCHAIN=nightly cargo build --release --locked --target wasm32-unknown-unknown --no-default-features --lib\n' +
      '     wasm-bindgen --target web --out-dir pkg target/wasm32-unknown-unknown/release/hoverfly.wasm\n')
  }
}

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints,
  outdir: assets,
  entryNames: '[name]',
  bundle: true,
  format: 'esm',
  splitting: false,
  sourcemap: true,
  target: ['chrome120'],
  logLevel: 'info',
  define: {
    'process.env.NODE_ENV': '"production"',
    // Build version stamped into the daemon SharedWorker URL + name so a new
    // deploy spawns a FRESH worker instead of rejoining the stale instance a
    // browser keeps alive across reloads (SharedWorker is keyed by origin +
    // script URL + name and persists until every client closes). Derived from
    // the vendored wasm's content hash, since the daemon going stale only
    // matters when the wasm changes; falls back to the build timestamp.
    __GW_VERSION__: JSON.stringify(daemonVersion())
  }
}

/** Short content hash of the vendored wasm (the thing whose change makes a
 *  running daemon stale). Falls back to the build time if pkg/ isn't present
 *  yet (the wasm is vendored just below in copyStatic). */
function daemonVersion () {
  try {
    const wasm = readFileSync(resolve(pkg, 'hoverfly_bg.wasm'))
    return createHash('sha256').update(wasm).digest('hex').slice(0, 12)
  } catch {
    return 't' + Date.now().toString(36)
  }
}

rmSync(dist, { recursive: true, force: true })
mkdirSync(assets, { recursive: true })
copyStatic()

if (watch) {
  const ctx = await esbuild.context(options)
  await ctx.watch()
  // re-copy static on a simple interval is overkill; copy once and rely on
  // editing public/ rarely. Re-run `npm run build` for static changes.
  console.log('esbuild watching for changes…')
} else {
  await esbuild.build(options)
  console.log('built →', dist)
}
